// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-7ySJeqJ07s_haBsY10luoCMITuh0-r4',
    appId: '1:957127067434:web:3131329b7a6526d3508053',
    messagingSenderId: '957127067434',
    projectId: 'prueba-tecnica-sic4',
    authDomain: 'prueba-tecnica-sic4.firebaseapp.com',
    storageBucket: 'prueba-tecnica-sic4.appspot.com',
    measurementId: 'G-01E0NENKW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFZHkj46PCabEgJsaiJi_bJbHioh3jRM',
    appId: '1:957127067434:android:f6f44c6d062068d9508053',
    messagingSenderId: '957127067434',
    projectId: 'prueba-tecnica-sic4',
    storageBucket: 'prueba-tecnica-sic4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpgKr_HXYivvPkO2ZYu4GeOLcU6m5UW-0',
    appId: '1:957127067434:ios:9f78893d640d59bd508053',
    messagingSenderId: '957127067434',
    projectId: 'prueba-tecnica-sic4',
    storageBucket: 'prueba-tecnica-sic4.appspot.com',
    iosClientId: '957127067434-nsmv05u8eedreclrkflul9m66misft29.apps.googleusercontent.com',
    iosBundleId: 'com.example.sic4changePrueba',
  );
}
